### PR TITLE
fix vulnerability

### PR DESCRIPTION
**Pull request by testwill**

### CODE REVIEW

**Comment by craigbox** [comment]
Hey @testwill,

Thanks for looking at this.  Can you please provide some context as to what tool you used, or what specific vulnerability/ies you were trying to fix?

**Comment by testwill** [comment]
trivy

**Comment by testwill** [comment]
kubescape image had  some  vulnerability/ies

**Comment by testwill** [comment]
image

**Review by dwertent — APPROVED** [review]

**Comment by dwertent** [comment]
Thank you @testwill , 
I'm closing this because we have bumped many packages in this PR #128

**Pull request closed without merging**
