### PR TITLE
chore(lint): introduced linting

### LINKED ISSUE #77: Proposal: enforce minimal linting rules
I propose to follow the basic principles that were adopted for github.com/kubescape/kubescape and introduce minimal code standards to this repository.

See my PR proposal: #76 

NOTE: I now realize that most of the impact here concerns the regostore, which has now migrated to github.com/kubescape/regolibrary. Since that one remains for now a plain copy of this repo, I'll propose similar improvements there.

cc: @matthyx @dwertent @vladklokun

### PR DESCRIPTION
**Pull request by fredbi**
* introduced linting enforced by CI
* fixed linting issues
* added: lock obviously missing, preallocated slices

(followed the same set of rules as defined for kubescape/kubescape)

* fixes #77 

Signed-off-by: Frédéric BIDON <fredbi@yahoo.com>

### CODE REVIEW

**Review by dwertent — APPROVED** [review]
We will add a central workflow for all the Kubescape-related packages. We will be adding the linting checks to that workflow :)

**Comment by fredbi** [comment]
@dwertent  I am rebasing but CI no longer passes since you have merged #78 (fix is #80 ). Would you mind merging #80  first so we get back to a regular CI "green" status? Cheers

**Comment by fredbi** [comment]
@matthyx @dwertent  rebased

**Review by matthyx — APPROVED** [review]

**Comment by matthyx** [comment]
@dwertent since we have the global CI workflow, do we still need that PR?

**Comment by fredbi** [comment]
@matthyx  the change to the github workflow might be unnecessary. However, there are still some code changes...

**Review by dwertent — APPROVED** [review]

**Pull request merged**
