### PR TITLE
Change type of ScanMetadata.Format to `slice of strings` from `string`

### PR DESCRIPTION
**Pull request by suhasgumma**
* This change is required to support getting outputs in multiple formats.

### CODE REVIEW

**Comment by amirmalka** [comment]
@suhasgumma @vladklokun please note that changing an existing field type would cause unmarshalling errors in the BE, as it continues to support old versions of ScanMetadata.

In this case, I would create a new field and deprecate the old one.

**Comment by vladklokun** [comment]
@amirmalka

> In this case, I would create a new field and deprecate the old one.
Yup, that is our intention. I will be taking over this PR, so if you have any comments, please feel free to reach out to me.

**Comment by dwertent** [comment]
cc: @vladklokun

**Comment by vladklokun** [comment]
@suhasgumma 

For future reference, when you open a PR, it’s best to create a new branch inside your fork that contains the changes you suggest, instead of pushing directly into the fork’s master. This avoids a lot of inconveniences when trying to keep the feature branch in sync with upstream’s master. For example, pulling updates from upstream master, rebasing onto upstream master etc.

Atlassian has a good [guide](https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow) on how to use the Forking Workflow.

**Comment by suhasgumma** [comment]
Thank you Vlad!! I'll keep that in mind in the future.

**Review by dwertent — APPROVED** [review]

**Pull request merged**
