### PR TITLE
Fix #1051 memory profile (global free, API breaking change)

### PR DESCRIPTION
**Pull request by fredbi**

### CODE REVIEW

**Comment by fredbi** [comment]
Same intent as #74, but with a privately held cache and no globals. The exception processing interface is affected.

cc: @dwertent @matthyx

**Comment by matthyx** [comment]
Interface changes LGTM, I think you can move forward.
So you deprecate #74 in favor of this one?
I am still not sure whether the tuple (DesignatorType, WLID, WildWLID, SID) is unique... @amirmalka ?

**Comment by fredbi** [comment]
@matthyx cleaned and squashed everything

**Review by matthyx — APPROVED** [review]
@dwertent LGTM I let you merge tomorrow if you agree

**Comment by matthyx** [comment]
> @matthyx cleaned and squashed everything

looks good thanks a lot Fred! I'll let David check as well.

**Comment by fredbi** [comment]
@matthyx @dwertent reflecting on the rather weak hashing function I have introduced (simply summing the hashes of a set into a larger integer), I admit that I am a bit wary of the likelihood of hash collisions here.

I'd need a little time to survey the literature and find a stronger, yet still memory-efficient way of hashing an unordered set.  Something like this https://people.csail.mit.edu/devadas/pubs/mhashes.pdf

I believe that the current method is good enough for what we do. Anyhow, I'm going to work on improving that part next week, in a separate "improvement" PR for the sake of clarity.

**Comment by fredbi** [comment]
> @matthyx @dwertent reflecting on the rather weak hashing function I have introduced (simply summing the hashes of a set into a larger integer), I admit that I am a bit wary of the likelihood of hash collisions here.

@matthyx @dwertent I've improved the inner hash used by the cache (#82), to implement set-hashing in a more thorough way.

**Comment by dwertent** [comment]
Well done @fredbi !!

**Review by dwertent — APPROVED** [review]

**Comment by fredbi** [comment]
@matthyx @matthyx  thank you so much.

There is a follow-up on that one: #82 , which strengthens the hash function. I am okay with refactoring it if you think that the gory details of finite field arithmetic should be offloaded ... :)

**Pull request merged**
