### PR TITLE
fix(regostore): race conditions

### PR DESCRIPTION
**Pull request by fredbi**

### CODE REVIEW

**Review by dwertent — APPROVED** [review]
I merged this PR because of the change that was introduced in the GH workflows

/cc @kooomix

**Comment by fredbi** [comment]
@dwertent  ok will push against the new repo.

However, last time I checked, the regolibrary had a dependency on the kubescape repo, thus preventing imports from kubescape... Have to check this again.

**Comment by fredbi** [comment]
@dwertent  this PR was demonstrating the failure... :) 
A solution is proposed in #80

**Comment by kooomix** [comment]
@fredbi @dwertent 
1. In the last regolibrary updated we have removed completely the dependency on kubescape repo.
2. As for moving gitregostore to regolibrary - although we have copied it to regolibrary, we still didn't merge it to kubescape and cadashboardbe repos since we go into a test failure in windows on [this](https://github.com/kubescape/kubescape/pull/1058) pr that we haven't yet resolved, so meanwhile we will continue work on gitregostore in opa-utils, and later on make sure to update it's new location with the updated version.

sorry for the confusion.

**Pull request merged**
